defaults:
  - model: Your-Chosen-Model
  - data: Your-Chosen-DataSet
  - utils: default
  - logging: wandb
  - _self_

hydra:
  run:
    dir: ${utils.output_config_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}